### PR TITLE
Fix Small Device Responsiveness

### PR DESCRIPTION
**Pull request by kunaljaykam**
>Assignments > AdList Milestone #1  page wasn't responsive on smartphone screens (Please do check before merging it)

### CODE REVIEW

**Comment by csev** [comment]
Thanks - I did not even know that was possible :)  I am guessing this should be in a lot of places in my web sites.  Feel free to find them and fix them :).

**Comment by kunaljaykam** [comment]
> Thanks - I did not even know that was possible :) I am guessing this should be in a lot of places in my web sites. Feel free to find them and fix them :).

No Problem @csev 
Actually, this has been solved in bootstrap 4, but since **tsugi** is still on bootstrap 3, Therefore the problem :)

**Comment by kunaljaykam** [comment]
Unfortunately, it's working on the production, So now to fix it permanently and some others too, I will just update the static tsugi to **bootstrap 4**

**Comment by csev** [comment]
If you are willing to test it all carefully - I would be happy to move forward.   But  there is a lot of markup to test.  We could add bootstrap 4 to Tsugi static to make the experimentation easier.

**Pull request merged**
