### PR TITLE
Fix typo in assn/dj4e_hello.md

### PR DESCRIPTION
**Pull request by jmorakuebler**
Fix typo in line 48 of the assn/dj4e_hello.md file.

### CODE REVIEW

**Comment by csev** [comment]
Thanks for the fix.

**Comment by jmorakuebler** [comment]
And thank you for the superb content of your courses. Glad to help!

**Comment by csev** [comment]
You are quite welcome.  If you look at https://www.dj4e.com/assn/dj4e_hello.md it has already been updated for students all around the world.

**Comment by jmorakuebler** [comment]
Awesome. I'll keep an :eye: on the lectures to see if there's anything else I can help you with!

**Pull request merged**
